### ISSUE TITLE
Question about the finetuning

### ISSUE THREAD

**Issue by Aziily** [desaixie/pa_vdm#3]
Thanks for your great work. But I have a question about the finetuning part in your paper. As depicted, you finetune the original model with a linear noise schedule. How do you design the training process? Because there is difference between the training steps and inference steps, I think just sampling two timesteps randomly and interpolating linearly may not satisfy the training requirements?

Can you share some insights with me? Or when will you make the code open source for reference?

**Comment by desaixie** [comment]
The training timesteps are set to the inference timesteps plus some perturbation, in order to adapt the model to our progressive noise levels while ensuring full coverage of $(0, T)$. For example, when $T=1$ and $F=S=30$, then a linear inference timestep schedule would be $1, 0.966, 0.933, ..., 0.066, 0.033$
```python
T = 1.
num_sampling_steps = num_latent_frames = 30
sample_timesteps = torch.linspace(T/num_sampling_steps, T, num_sampling_steps)  # (S,)
for t in sample_timesteps.flip(0):
    # do sampling
```
and the training timesteps would be
```python
# inside one training step
sample_timestep_gap = T / num_sampling_steps
perturb = 0.4 * sample_timestep_gap * torch.randn((1,)).repeat(num_latent_frames)  # (S,)
train_timesteps = (sample_timesteps + perturb).clamp(0, T)  # (F,)
# do forward, backward
```

**Comment by Aziily** [comment]
Thank you for sharing.
